export interface MathSymbolItem {
  id: string;
  symbol: string; // LaTeX code for KaTeX rendering
  name: string; // Nama resmi simbol
  pronunciation: string; // Cara baca dalam Bahasa Indonesia sehari-hari
  plainMeaning: string; // Penjelasan ringkas untuk orang awam
  exampleLatex: string; // Contoh penulisan ekspresi
  exampleReading: string; // Cara membaca contoh rumus
  category: MathSymbolCategory;
  visualNicknames?: string[]; // Sebutan awam berdasarkan bentuk visual (contoh: "angka 8 tidur", "cacing", "segitiga terbalik")
}

export const MATH_SYMBOL_CATEGORIES = [
  "Semua",
  "Dasar & Operasi",
  "Himpunan & Logika",
  "Aljabar & Fungsi",
  "Kalkulus",
  "Vektor & Geometri",
] as const;

export type MathSymbolCategory = (typeof MATH_SYMBOL_CATEGORIES)[number];

export const MATH_SYMBOLS_DATABASE: MathSymbolItem[] = [
  // --- Dasar & Operasi ---
  {
    id: "sym-pm",
    symbol: "\\pm",
    name: "Plus-Minus",
    pronunciation: "plus minus (kurang lebih)",
    plainMeaning: "Menandakan ada dua kemungkinan nilai: bisa ditambah (+) atau dikurang (-).",
    exampleLatex: "x = \\pm 3",
    exampleReading: "x sama dengan plus minus 3 (artinya x = 3 atau x = -3)",
    category: "Dasar & Operasi",
    visualNicknames: ["tambah kurang", "tanda plus di atas minus", "kurang lebih"],
  },
  {
    id: "sym-approx",
    symbol: "\\approx",
    name: "Hampir Sama Dengan",
    pronunciation: "kira-kira sama dengan / mendekati",
    plainMeaning: "Digunakan saat nilai hasil merupakan taksiran/pembulatan, bukan nilai eksak.",
    exampleLatex: "\\pi \\approx 3{,}14",
    exampleReading: "pi mendekati tiga koma satu empat",
    category: "Dasar & Operasi",
    visualNicknames: ["gelombang", "ombak dua garis", "sama dengan bergelombang", "taksiran", "kira kira"],
  },
  {
    id: "sym-neq",
    symbol: "\\neq",
    name: "Tidak Sama Dengan",
    pronunciation: "tidak sama dengan",
    plainMeaning: "Menunjukkan dua nilai atau ekspresi di kiri dan kanan tidak bernilai sama.",
    exampleLatex: "x \\neq 0",
    exampleReading: "x tidak sama dengan nol",
    category: "Dasar & Operasi",
    visualNicknames: ["sama dengan dicoret", "coret garis miring", "bukan sama dengan"],
  },
  {
    id: "sym-le-ge",
    symbol: "\\le, \\ge",
    name: "Kurang/Lebih Dari Sama Dengan",
    pronunciation: "kurang dari atau sama dengan / lebih dari atau sama dengan",
    plainMeaning: "Batas nilai di mana angka batasnya sendiri juga termasuk.",
    exampleLatex: "x \\le 5",
    exampleReading: "x kurang dari atau sama dengan 5 (5 masih termasuk)",
    category: "Dasar & Operasi",
    visualNicknames: ["lancip garis bawah", "kurang dari", "lebih dari", "moncong"],
  },
  {
    id: "sym-abs",
    symbol: "|x|",
    name: "Nilai Mutlak",
    pronunciation: "nilai mutlak dari x / modulus x",
    plainMeaning: "Jarak suatu angka dari angka 0 pada garis bilangan, nilainya selalu positif atau nol.",
    exampleLatex: "|-7| = 7",
    exampleReading: "nilai mutlak dari minus tujuh sama dengan tujuh",
    category: "Dasar & Operasi",
    visualNicknames: ["dua garis tegak", "pagar", "diapit garis lurus", "modulus"],
  },
  {
    id: "sym-prop",
    symbol: "\\propto",
    name: "Proporsional",
    pronunciation: "sebanding dengan / berbanding lurus dengan",
    plainMeaning: "Jika variabel satu membesar, variabel lainnya juga membesar secara proporsional.",
    exampleLatex: "F \\propto a",
    exampleReading: "Gaya (F) sebanding dengan percepatan (a)",
    category: "Dasar & Operasi",
    visualNicknames: ["seperti ikan", "huruf alfa tidur", "sebanding"],
  },

  // --- Himpunan & Logika ---
  {
    id: "sym-in",
    symbol: "\\in",
    name: "Elemen / Keanggotaan",
    pronunciation: "anggota dari / elemen dari",
    plainMeaning: "Menyatakan bahwa suatu objek berada di dalam kelompok/himpunan tertentu.",
    exampleLatex: "x \\in \\mathbb{R}",
    exampleReading: "x adalah anggota himpunan bilangan real",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf e melengkung", "seperti huruf c ada garis tengah", "euro kecil", "anggota"],
  },
  {
    id: "sym-notin",
    symbol: "\\notin",
    name: "Bukan Elemen",
    pronunciation: "bukan anggota dari",
    plainMeaning: "Menyatakan objek tersebut tidak ada di dalam kelompok/himpunan itu.",
    exampleLatex: "-2 \\notin \\mathbb{N}",
    exampleReading: "minus dua bukan anggota bilangan asli",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf e dicoret", "bukan anggota", "c dicoret tengah"],
  },
  {
    id: "sym-subset",
    symbol: "\\subset",
    name: "Himpunan Bagian (Subset)",
    pronunciation: "bagian dari / himpunan bagian dari",
    plainMeaning: "Semua isi kelompok A juga ada di dalam kelompok B.",
    exampleLatex: "A \\subset B",
    exampleReading: "himpunan A adalah himpunan bagian dari B",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf c melebar", "tapal kuda tidur", "subset"],
  },
  {
    id: "sym-cup",
    symbol: "\\cup",
    name: "Gabungan (Union)",
    pronunciation: "gabungan / union",
    plainMeaning: "Menggabungkan semua anggota kelompok A dan kelompok B jadi satu kelompok baru.",
    exampleLatex: "A \\cup B",
    exampleReading: "A gabungan B",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf u", "mangkuk menghadap atas", "cangkir", "union", "gabungan"],
  },
  {
    id: "sym-cap",
    symbol: "\\cap",
    name: "Irisan (Intersection)",
    pronunciation: "irisan / interseksi",
    plainMeaning: "Hanya mengambil anggota yang dimiliki bersama oleh kelompok A dan B sekaligus.",
    exampleLatex: "A \\cap B",
    exampleReading: "irisan A dan B",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf n", "mangkuk terbalik", "atap lengkung", "irisan"],
  },
  {
    id: "sym-emptyset",
    symbol: "\\emptyset",
    name: "Himpunan Kosong",
    pronunciation: "himpunan kosong",
    plainMeaning: "Kelompok atau himpunan yang sama sekali tidak memiliki anggota.",
    exampleLatex: "A \\cap B = \\emptyset",
    exampleReading: "irisan A dan B adalah himpunan kosong (tidak ada yang sama)",
    category: "Himpunan & Logika",
    visualNicknames: ["lingkaran dicoret", "angka nol dicoret garis miring", "kosong", "bulat coret"],
  },
  {
    id: "sym-forall",
    symbol: "\\forall",
    name: "Kuantor Universal",
    pronunciation: "untuk semua / untuk setiap",
    plainMeaning: "Aturan atau rumus ini berlaku untuk seluruh anggota tanpa pengecualian.",
    exampleLatex: "\\forall x > 0",
    exampleReading: "untuk setiap x yang lebih besar dari nol",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf a terbalik", "a kebalik", "segitiga terbalik ada tanduk", "untuk semua"],
  },
  {
    id: "sym-exists",
    symbol: "\\exists",
    name: "Kuantor Eksistensial",
    pronunciation: "ada / terdapat setidaknya satu",
    plainMeaning: "Menjamin ada minimal satu objek yang memenuhi syarat yang disebutkan.",
    exampleLatex: "\\exists x, \\; x^2 = 4",
    exampleReading: "ada nilai x sedemikian sehingga x kuadrat sama dengan empat",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf e terbalik", "e hadap kiri", "e kebalik", "ada", "terdapat"],
  },
  {
    id: "sym-implies",
    symbol: "\\implies",
    name: "Implikasi Logika",
    pronunciation: "maka / berakibat / mengimplikasikan",
    plainMeaning: "Jika pernyataan di kiri benar, maka pernyataan di kanan pasti terjadi.",
    exampleLatex: "p \\implies q",
    exampleReading: "jika p maka q",
    category: "Himpunan & Logika",
    visualNicknames: ["panah ke kanan", "panah tebal", "panah garis ganda", "maka"],
  },
  {
    id: "sym-iff",
    symbol: "\\iff",
    name: "Biimplikasi (Ekuivalen)",
    pronunciation: "jika dan hanya jika",
    plainMeaning: "Kondisi kiri dan kanan saling mengikat timbal balik dua arah.",
    exampleLatex: "A \\iff B",
    exampleReading: "A jika dan hanya jika B",
    category: "Himpunan & Logika",
    visualNicknames: ["panah dua arah", "panah bolak balik", "panah kiri kanan"],
  },
  {
    id: "sym-real",
    symbol: "\\mathbb{R}",
    name: "Himpunan Bilangan Real",
    pronunciation: "bilangan real (R)",
    plainMeaning: "Semua bilangan yang ada di garis bilangan: positif, negatif, pecahan, akar, desimal.",
    exampleLatex: "x \\in \\mathbb{R}",
    exampleReading: "x adalah bilangan real",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf r garis ganda", "r dua garis", "real"],
  },
  {
    id: "sym-integers",
    symbol: "\\mathbb{Z}",
    name: "Himpunan Bilangan Bulat",
    pronunciation: "bilangan bulat (Z / Zahlen)",
    plainMeaning: "Bilangan utuh tanpa koma/pecahan, mencakup angka negatif, nol, dan positif (..., -2, -1, 0, 1, 2, ...).",
    exampleLatex: "n \\in \\mathbb{Z}",
    exampleReading: "n adalah bilangan bulat",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf z garis ganda", "z dua garis", "bilangan bulat"],
  },
  {
    id: "sym-naturals",
    symbol: "\\mathbb{N}",
    name: "Himpunan Bilangan Asli",
    pronunciation: "bilangan asli (N / Natural)",
    plainMeaning: "Bilangan bulat positif yang biasa dipakai untuk mencacah (1, 2, 3, 4, ...).",
    exampleLatex: "n \\in \\mathbb{N}",
    exampleReading: "n adalah bilangan asli",
    category: "Himpunan & Logika",
    visualNicknames: ["huruf n garis ganda", "n dua garis", "bilangan cacah asli"],
  },

  // --- Aljabar & Fungsi ---
  {
    id: "sym-comp",
    symbol: "\\circ",
    name: "Komposisi Fungsi (Bundaran)",
    pronunciation: "bundaran / komposisi",
    plainMeaning: "Memasukkan hasil dari fungsi g ke dalam fungsi f (berantai).",
    exampleLatex: "(f \\circ g)(x) = f(g(x))",
    exampleReading: "f bundaran g dari x sama dengan f dari g(x)",
    category: "Aljabar & Fungsi",
    visualNicknames: ["bundaran kecil", "lingkaran kecil di tengah", "titik bolong", "derajat tengah"],
  },
  {
    id: "sym-sigma",
    symbol: "\\sum",
    name: "Sigma (Notasi Penjumlahan)",
    pronunciation: "sigma / jumlahan dari...",
    plainMeaning: "Perintah menjumlahkan deretan suku angka berurutan dari suku awal sampai akhir.",
    exampleLatex: "\\sum_{i=1}^n x_i",
    exampleReading: "jumlahan x sub-i dari i sama dengan satu sampai n",
    category: "Aljabar & Fungsi",
    visualNicknames: ["huruf e lancip", "huruf m miring", "seperti huruf w berdiri", "sigma", "total jumlahan"],
  },
  {
    id: "sym-prod",
    symbol: "\\prod",
    name: "Notasi Perkalian (Pi Besar)",
    pronunciation: "produk dari / perkalian berurutan",
    plainMeaning: "Mirip sigma, namun operasinya dikalikan terus-menerus.",
    exampleLatex: "\\prod_{i=1}^n i = n!",
    exampleReading: "perkalian i dari satu sampai n sama dengan n faktorial",
    category: "Aljabar & Fungsi",
    visualNicknames: ["pintu gerbang", "tiang gawang", "huruf pi besar", "gapura"],
  },
  {
    id: "sym-factorial",
    symbol: "n!",
    name: "Faktorial",
    pronunciation: "n faktorial",
    plainMeaning: "Perkalian mundur dari angka n sampai angka 1 (contoh: 4! = 4 x 3 x 2 x 1 = 24).",
    exampleLatex: "5! = 120",
    exampleReading: "lima faktorial sama dengan seratus dua puluh",
    category: "Aljabar & Fungsi",
    visualNicknames: ["tanda seru", "titik di bawah garis", "faktorial"],
  },
  {
    id: "sym-sqrt",
    symbol: "\\sqrt{x}",
    name: "Akar Kuadrat",
    pronunciation: "akar dari x / akar kuadrat x",
    plainMeaning: "Mencari angka yang jika dikalikan dengan dirinya sendiri menghasilkan x.",
    exampleLatex: "\\sqrt{25} = 5",
    exampleReading: "akar dari dua puluh lima sama dengan lima",
    category: "Aljabar & Fungsi",
    visualNicknames: ["tanda centang ada atap", "centang panjang", "akar"],
  },
  {
    id: "sym-ln",
    symbol: "\\ln(x)",
    name: "Logaritma Natural",
    pronunciation: "len dari x / logaritma natural x",
    plainMeaning: "Logaritma khusus yang menggunakan basis bilangan konstan Euler e (sekitar 2,718).",
    exampleLatex: "\\ln(e) = 1",
    exampleReading: "len dari e sama dengan satu",
    category: "Aljabar & Fungsi",
    visualNicknames: ["tulisan ln", "in kecil", "logaritma"],
  },
  {
    id: "sym-pi",
    symbol: "\\pi",
    name: "Pi (Konstanta Lingkaran)",
    pronunciation: "pi (sekitar 3,14159)",
    plainMeaning: "Perbandingan keliling lingkaran apa pun terhadap garis tengah (diameternya).",
    exampleLatex: "L = \\pi r^2",
    exampleReading: "Luas sama dengan pi kali r kuadrat",
    category: "Aljabar & Fungsi",
    visualNicknames: ["dua kaki ada atap mendatar", "meja kecil", "pi", "phi"],
  },

  // --- Kalkulus ---
  {
    id: "sym-lim",
    symbol: "\\lim_{x \\to a}",
    name: "Limit",
    pronunciation: "limit untuk x mendekati a dari...",
    plainMeaning: "Melihat kecenderungan nilai fungsi saat inputnya didekati sedekat-dekatnya ke angka a.",
    exampleLatex: "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1",
    exampleReading: "limit sin x per x untuk x mendekati nol sama dengan satu",
    category: "Kalkulus",
    visualNicknames: ["tulisan lim", "panah mendekati", "limit"],
  },
  {
    id: "sym-deriv",
    symbol: "\\frac{df}{dx}, \\; f'(x)",
    name: "Turunan / Diferensial",
    pronunciation: "turunan f terhadap x / f aksen x",
    plainMeaning: "Mengukur laju perubahan sesaat (kecepatan perubahan) nilai fungsi f saat x bergeser sedikit.",
    exampleLatex: "\\frac{d}{dx}(x^2) = 2x",
    exampleReading: "turunan dari x kuadrat terhadap x sama dengan dua x",
    category: "Kalkulus",
    visualNicknames: ["petik satu di atas", "aksen", "d per dx", "turunan"],
  },
  {
    id: "sym-partial",
    symbol: "\\partial",
    name: "Turunan Parsial",
    pronunciation: "parsial f terhadap x / del f del x",
    plainMeaning: "Menurunkan fungsi banyak variabel dengan menganggap variabel lainnya sementara sebagai angka tetap.",
    exampleLatex: "\\frac{\\partial z}{\\partial x}",
    exampleReading: "turunan parsial z terhadap x",
    category: "Kalkulus",
    visualNicknames: ["huruf d melengkung", "angka 6 terbalik", "d keriting", "del"],
  },
  {
    id: "sym-integral",
    symbol: "\\int f(x) \\, dx",
    name: "Integral Tak Tentu",
    pronunciation: "integral dari f(x) terhadap x",
    plainMeaning: "Proses kebalikan dari turunan (antiturunan) untuk merekonstruksi kembali fungsi asal.",
    exampleLatex: "\\int 2x \\, dx = x^2 + C",
    exampleReading: "integral dari dua x dx sama dengan x kuadrat ditambah konstanta C",
    category: "Kalkulus",
    visualNicknames: ["cacing berdiri", "huruf s panjang", "gagang payung", "integral"],
  },
  {
    id: "sym-def-integral",
    symbol: "\\int_a^b f(x) \\, dx",
    name: "Integral Tentu",
    pronunciation: "integral dari a sampai b untuk f(x) dx",
    plainMeaning: "Menghitung luas total daerah di bawah kurva grafik f(x) dari batas bawah a sampai batas atas b.",
    exampleLatex: "\\int_0^2 x \\, dx = 2",
    exampleReading: "integral dari nol sampai dua untuk x dx sama dengan dua",
    category: "Kalkulus",
    visualNicknames: ["cacing ada angka atas bawah", "integral ada batas", "luas daerah"],
  },
  {
    id: "sym-delta",
    symbol: "\\Delta",
    name: "Delta (Selisih / Perubahan)",
    pronunciation: "delta x / selisih nilai x",
    plainMeaning: "Perubahan atau selisih antara nilai akhir dikurangi nilai awal (x_akhir - x_awal).",
    exampleLatex: "m = \\frac{\\Delta y}{\\Delta x}",
    exampleReading: "gradien m sama dengan delta y dibagi delta x",
    category: "Kalkulus",
    visualNicknames: ["segitiga", "segitiga sama sisi", "delta", "selisih"],
  },
  {
    id: "sym-infty",
    symbol: "\\infty",
    name: "Tak Hingga (Infinity)",
    pronunciation: "tak hingga / tak terhingga",
    plainMeaning: "Bukan sebuah angka, melainkan konsep jumlah atau besaran yang terus membesar tanpa pernah berujung.",
    exampleLatex: "x \\to \\infty",
    exampleReading: "x menuju tak hingga (x membesar tanpa batas)",
    category: "Kalkulus",
    visualNicknames: ["angka 8 tidur", "angka 8 miring", "kacamata tidur", "pita tidur", "infinity", "tak hingga"],
  },

  // --- Vektor & Geometri ---
  {
    id: "sym-vector",
    symbol: "\\vec{v}",
    name: "Notasi Vektor",
    pronunciation: "vektor v",
    plainMeaning: "Besaran yang memiliki nilai sekaligus memiliki arah tertentu di ruang.",
    exampleLatex: "\\vec{v} = (3, 4)",
    exampleReading: "vektor v dengan komponen tiga dan empat",
    category: "Vektor & Geometri",
    visualNicknames: ["panah di atas huruf", "topi panah", "vektor"],
  },
  {
    id: "sym-norm",
    symbol: "\\|\\vec{v}\\|",
    name: "Panjang / Norma Vektor",
    pronunciation: "panjang vektor v / norma vektor v",
    plainMeaning: "Jarak lurus mutlak dari titik pangkal ke ujung panah vektor tersebut.",
    exampleLatex: "\\|\\vec{v}\\| = \\sqrt{x^2 + y^2}",
    exampleReading: "panjang vektor v sama dengan akar x kuadrat tambah y kuadrat",
    category: "Vektor & Geometri",
    visualNicknames: ["garis ganda kiri kanan", "dua pasang pagar", "norma", "panjang"],
  },
  {
    id: "sym-det",
    symbol: "\\det(A), \\; |A|",
    name: "Determinan Matriks",
    pronunciation: "determinan dari matriks A",
    plainMeaning: "Nilai skalar tunggal dari matriks persegi yang mengukur faktor penskalaan ruang atau volume.",
    exampleLatex: "\\det(A) = ad - bc",
    exampleReading: "determinan A sama dengan a kali d dikurang b kali c",
    category: "Vektor & Geometri",
    visualNicknames: ["tulisan det", "matriks diapit garis lurus", "determinan"],
  },
  {
    id: "sym-nabla",
    symbol: "\\nabla",
    name: "Nabla / Del",
    pronunciation: "nabla / gradien operator",
    plainMeaning: "Operator turunan vektor ruang tiga dimensi yang menunjukkan arah pendakian paling curam.",
    exampleLatex: "\\nabla f",
    exampleReading: "gradien dari fungsi f",
    category: "Vektor & Geometri",
    visualNicknames: ["segitiga terbalik", "segitiga kebalik", "corong terbalik", "nabla"],
  },
  {
    id: "sym-theta",
    symbol: "\\theta",
    name: "Teta (Sudut)",
    pronunciation: "teta",
    plainMeaning: "Huruf Yunani standar internasional untuk melambangkan besar sudut trigonometri.",
    exampleLatex: "\\sin \\theta, \\; \\cos \\theta",
    exampleReading: "sinus teta, kosinus teta",
    category: "Vektor & Geometri",
    visualNicknames: ["lingkaran ada garis tengah", "telur ceplok", "angka nol ada sabuk", "teta", "sudut"],
  },
  {
    id: "sym-perp",
    symbol: "\\perp",
    name: "Tegak Lurus (Perpendicular)",
    pronunciation: "tegak lurus terhadap",
    plainMeaning: "Dua garis atau vektor yang saling berpotongan membentuk sudut siku-siku tepat 90 derajat.",
    exampleLatex: "L_1 \\perp L_2",
    exampleReading: "garis L satu tegak lurus terhadap garis L dua",
    category: "Vektor & Geometri",
    visualNicknames: ["huruf t terbalik", "t kebalik", "tegak lurus", "siku siku"],
  },
  {
    id: "sym-parallel",
    symbol: "\\parallel",
    name: "Sejajar (Parallel)",
    pronunciation: "sejajar dengan",
    plainMeaning: "Dua garis yang memiliki arah dan kemiringan yang sama persis sehingga tidak akan pernah berpotongan.",
    exampleLatex: "A \\parallel B",
    exampleReading: "garis A sejajar dengan garis B",
    category: "Vektor & Geometri",
    visualNicknames: ["dua garis tegak", "dua garis miring sejajar", "rel kereta", "sejajar"],
  },
];
